
spring.application.name=smartdining

# MySQL Database

spring.datasource.url=jdbc:mysql://localhost:3306/savordine?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true

spring.datasource.username=root

spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# JPA / Hibernate

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# Server

server.port=8080


# Admin Login

admin.username=admin

admin.password=suriya3026
server.port=${PORT:8080}
